config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :sessions, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/users/:id/edit-restricted', to: 'users#edit_restricted', as: 'edit_restricted'
  patch '/users/:id/edit-restricted', to: 'users#update_restricted'

  get '/users/:id/edit-kitchen', to: 'users#edit_kitchen', as: 'edit_kitchen'
  patch '/users/:id/edit-kitchen', to: 'users#update_kitchen'

  root 'users#show'
  get '/home', to: 'sessions#index', as: 'home'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users #, except: [:update, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :user_ingredients
  has_many :users, through: :user_ingredients
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  def self.category(cat)
    Ingredient.all.select {|ing| ing.category == cat}
  end

  def self.categories
    Ingredient.all.map {|ing| ing.category}.uniq
  end

  def self.category_sort
    sorted = {}
    #array of category names
    Ingredient.categories.each do |cat|
      #each cat name set to a key w/ value = corresponding ingredient objects
      sorted[cat] = Ingredient.category(cat)
    end
    sorted.values.flatten
  end

end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  def self.user_filtered(user)
    # array of hashes to return
    final = []
    # loop over each recipe
    self.all.each do |recipe|
      unless !(recipe.ingredients & user.restricted_ings).empty?
        recipe_hash = {}
        recipe_hash[:recipe] = recipe
        # count number of recipe ingredients missing from user's kitchen
        diff = recipe.ingredients - user.kitchen
        recipe_hash[:missing] = diff.length
        final << recipe_hash
      end
    end
    # return sorted array
    final = final.sort_by { |recipe| recipe[:missing] }
  end

  def self.user_include_restrictions(user)
    # array of hashes to return
    final = []
    # loop over each recipe
    self.all.each do |recipe|
        recipe_hash = {}
        recipe_hash[:recipe] = recipe
        # count number of recipe ingredients missing from user's kitchen
        diff = recipe.ingredients - user.kitchen
        recipe_hash[:missing] = diff.length
        final << recipe_hash
    end
    # return sorted array
    final = final.sort_by { |recipe| recipe[:missing] }
    final
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/restriction.rb
class Restriction < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_ingredients
  has_many :ingredients, through: :user_ingredients
  has_secure_password
  accepts_nested_attributes_for :user_ingredients
  validates :username, presence: true, uniqueness: {case_sensitive: false}

  def name
    "#{self.first_name} #{self.last_name}"
  end

  def kitchen
    self.ingredients.merge(UserIngredient.where(relationship: "in_kitchen"))
  end

  def restricted_ings
    self.ingredients.merge(UserIngredient.where(relationship: "restricted"))
  end

end

app/models/user_ingredient.rb
class UserIngredient < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
  validates :relationship, inclusion: {in: %w(restricted in_kitchen)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :current_user

  def current_user
    if @current_user
      @current_user
    else
      @current_user = User.find_by(username: session[:username])
    end
  end

  def require_login
    redirect_to home_path unless !!current_user
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  def new
    @kitchen = Kitchen.new
  end

  def create
    byebug
    # overwrite current_user's Kitchen associations with form selections
    current_user.kitchens.destroy_all
    byebug
    params[:ingredient_ids].each do |ing_id|
      # byebug
      Kitchen.create(user_id: current_user.id, ingredient_id: ing_id)
      # byebug
    end
    redirect_to user_path(current_user)
  end

  def edit
    # byebug
    @kitchen = current_user.kitchens

    @user = current_user
  end

  def update

  end
end

private

def kitchen_params
  params.permit(ingredient_ids:[])
end

# def new_kitchen_params
#   selected(params[:kitchen][:ingredient_id])
# end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    # byebug
    if params[:restrictions] == "false"
      @recipes = Recipe.user_include_restrictions(current_user)
    else
      @recipes = Recipe.user_filtered(current_user)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/restrictions_controller.rb
class RestrictionsController < ApplicationController

  def edit

  end

  def update

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    # shows login or create account
  end

  def new
    # render login form
  end

  def create
    # create new session based on existing user
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:username] = @user.username
      redirect_to user_path(@user)
    else
      @error = "Invalid username or password"
      render :new
    end
  end

  def destroy
    session.delete(:username)
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]

  def new
    #get new account form
    @user = User.new
  end

  def create
    #post create new account
    @user = User.new
    if @user.update(new_user_params)
      session[:username] = @user.username
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
  end

  def edit_restricted
    @user = current_user
  end

  def update_restricted
    old = current_user.user_ingredients.where(relationship: "restricted")
    old.destroy_all
    add = selected(user_params[:ingredient_ids])
    add.each do |ing_id|
      UserIngredient.create(
        user: current_user,
        ingredient_id: ing_id,
        relationship: "restricted"
      )
    end
    redirect_to user_path(current_user)
  end

  def edit_kitchen
    @user = current_user
  end

  def update_kitchen
    old = current_user.user_ingredients.where(relationship: "in_kitchen")
    old.destroy_all
    add = selected(user_params[:ingredient_ids])
    #loop over ing_ids array and create user_ingredient instance for each (with self and corresponding relationship)
    add.each do |ing_id|
      UserIngredient.create(
        user: current_user,
        ingredient_id: ing_id,
        relationship: "in_kitchen"
      )
    end
    # byebug
    # current_user.ingredients = Ingredient.find(kitchen)
    redirect_to user_path(current_user)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(new_user_params)
      session[:username] = @user.username
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    
  end

  private

  def selected(arr)
    arr = arr[1..arr.length]
    arr.map { |e| e.to_i }
  end

  def user_params
    params.require(:user).permit(ingredient_ids:[])
  end

  def new_user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/restrictions_helper.rb
module RestrictionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kitchens/edit.html.erb
  <%= "edit page" %>

app/views/kitchens/new.html.erb
<h1><%= "#{current_user.first_name}'s Kitchen" %></h1>

<%= form_tag '/kitchens', method: :post do %>
  <% Ingredient.category_sort.each do |ing| %>
  <div>
    <%= check_box_tag 'ingredient_ids[]', ing.id, checked: current_user.kitchens.include?(ing.id)  %><%= ing.name %>
  </div>
  <% end %>

  <%= submit_tag %>
<% end %>

<!-- Array of all possible ingredients -->
<!-- If Ingredient.id is in Kitchens with current_user.id, select it -->
<!-- In params, return array of Ingredient id's -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smörgåsbord</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="app/assets/stylesheets/application.css">
  <link rel="stylesheet" href="app/assets/stylesheets/semantic.min.css">
</head>

<body>
  <div class="site-header">

    <h1><div class="header-title">Smörgåsbord</div></h1>
    <% if !current_user %>
    <h4><div class="sub-header">It's "what's for dinner?"</div></h4>
    <% end %>

    <% if current_user %>
      <%= form_tag logout_path, method: 'delete', class: 'welcome-prompt' do %>
        <div class="header-div">
          <p>Welcome, <%= current_user.first_name %></p>
        </div>
        <%= submit_tag "Logout", class: "ui compact inverted yellow button", id: "logout-button" %>
      <% end %>
      <% else %>
      <div class="welcome-prompt">
      <div class="welcome-prompt">
        </div>
        </div>
    <% end %>
    <!-- <div class="head-divider">
      <hr>
    </div> -->
  </div>

  <div class="site-body">
    <img src="https://vignette.wikia.nocookie.net/muppet/images/c/cd/Swed_chef_juggling.png/revision/latest?cb=20110325162545" class="bg-image">
    <%= yield %>
  </div>
</body>
</html>

app/views/recipes/index.html.erb
<h2>Recipes:</h2>

<div class="ui link list">
<ul>
  <% @recipes.each do |r| %>
    <li class="item"><%= link_to "#{r[:recipe][:name]} || You're missing #{pluralize(r[:missing], 'ingredient')}", recipe_path(r[:recipe]) %></li>
  <% end %>
</ul>
</div>

<%= link_to "Head back to the kitchen", user_path(current_user) %>

app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>

<h4>Ingredients:</h4>
<ul>
  <% @recipe.ingredients.each do |i| %>
    <li><%= i.name %></li>
  <% end %>
</ul>

<div>
  <%= link_to "See this recipe", @recipe.url, target: :_blank %>
</div>

<div>
  <%= link_to "Check out some other recipes", recipes_path %>
</div>

app/views/users/edit.html.erb
<p>Edit User</p>
<!-- Form to edit a user profile -->
<h2>Edit Profile</h2>

  <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
  <% end %>

    <%= form_for @user, action: 'update' do |f| %>
      <div>
        <%= f.label :username %>
          <%= f.text_field :username %>
      </div>
  <br>
      <div>
        <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        <%= f.label :last_name %>
          <%= f.text_field :last_name %>
      </div>
  <br>
        <%= f.submit %>

      <% end %>

app/views/users/edit_kitchen.html.erb
<div class="kitchen-edit-header"><h1><%= "#{current_user.first_name}'s Kitchen" %></h1></div>

<div class="ui form">

<%= form_for current_user, url: edit_kitchen_path, action: 'patch' do |f| %>


  <%= f.collection_check_boxes(:ingredient_ids, Ingredient.category_sort, :id, :name) do |ing| %>

    <div class="ui checkbox" >
      <%= ing.check_box checked: current_user.kitchen.include?(ing.object) %><%= ing.label { ing.text } %>
    </div><br>
  <% end %>
  <br>
  <div ><%= f.submit class:"ui blue button" %></div>
<% end %>
</div>



<% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
<% end %>

app/views/users/edit_restricted.html.erb
<h1><%= "#{current_user.first_name}'s Dietary Restrictions" %></h1>

<div class="ui form">
  <%= form_for current_user, url: edit_restricted_path, action: 'patch' do |f| %>
    <%= f.collection_check_boxes(:ingredient_ids, Ingredient.category_sort, :id, :name) do |ing| %>
      <div class="ui checkbox">
        <%= ing.check_box checked: current_user.restricted_ings.include?(ing.object) %><%= ing.label { ing.text } %>
      </div><br>
    <% end %>
    <br>
    <%= f.submit class:"ui blue button" %>
  <% end %>
</div>

app/views/users/new.html.erb
<!-- Form to create a new user -->
<div class="padding">

</div>
<h2>Create Account</h2>

  <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
  <% end %>

    <%= form_for @user, action: 'create' do |f| %>
      <div>
        <%= f.label :username %>
          <%= f.text_field :username %>
      </div>
  <br>
      <div>
        <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        <%= f.label :last_name %>
          <%= f.text_field :last_name %>
      </div>
  <br>
      <div>
        <%= f.label :password %>
          <%= f.password_field :password %>
        <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
      </div>
        <div class="padding"></div>
        <%= f.submit class:"ui blue button" %>

      <% end %>

app/views/users/show.html.erb
<h1><%= "#{current_user.first_name}'s Kitchen" %></h1>

<!-- List all of user's current items -->
<% if current_user.kitchen.count > 0 %>
  <ul class="ui bulleted list">
    <% current_user.kitchen.each do |ing| %>
      <li><%= ing.name %></li>
    <% end %>
  </ul>
<!-- If user has no items -->
<% else %>
  <p>Time to hit the grocery store! Your kitchen is empty.</p>
<% end %>

<!-- Link to edit current items -->
<div class="compact ui yellow button">
  <p><%= link_to "Need to update your kitchen?", edit_kitchen_path(current_user) %></p>
</div>

<!-- Link to show matching recipes -->
<div class="compact ui yellow button">
  <p><%= link_to "Update your Dietary Restrictions", edit_restricted_path(current_user) %></p>
</div>

<!--  -->
<div class="compact ui yellow button">
  <p><%= link_to "Show me what's for dinner (filter out restricted ingredients)", recipes_path(restrictions: true) %></p>
</div>

<div class="compact ui yellow button">
  <p><%= link_to "Show me all recipes (don't filter ingredients)", recipes_path(restrictions: false) %></p>
</div>